services:
  app:
    image: 'docker-spring-boot:latest'
    build:
      context: assignment/.
    env_file:
      - assignment/.env
    container_name: app
    ports:
      - "8080:8080"
  dashboard:
    image: 'dashboard-react-vite'
    build:
      context: interview-assignment-dashboard/.
    container_name: dashboard
    ports:
      - "5173:5173"